"""empty message

Revision ID: 6e4ecb7dcb80
Revises: 79f792834f55
Create Date: 2020-03-20 13:18:50.860240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e4ecb7dcb80'
down_revision = '79f792834f55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('inProgress', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'inProgress')
    # ### end Alembic commands ###
